name: CI/CD Docker

on:
  push:
    branches:
      - main

jobs:
  docker_build_deploy:   
    name: Docker Build & Deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        shell: bash
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tp5_docker:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/tp5_docker:latest

     
      - name: Deploy locally
        run: powershell -ExecutionPolicy Bypass -File ".\deploy.ps1"